### ISSUE TITLE
Question on relative_train_NCEV.txt

### ISSUE THREAD

**Issue by ansucatherine** [ZebangCheng/Emotion-LLaMA#34]
Dear Authors,

Thank you for sharing this great work and for your effort in making the code available!

While running the code, I encountered the following error:

> BaseDatasetBuilder data type: images
> 2024-12-20 21:53:22,795 [INFO] Building datasets...
> ann_path:  /home/user/selected_face/face_emotion/relative_train_NCEV.txt
> Traceback (most recent call last):
>   File "/data/hwj/EmotionRecognition/Emotion-LLaMA/train.py", line 99, in <module>
>     main()
>   File "/data/hwj/EmotionRecognition/Emotion-LLaMA/train.py", line 89, in main
>     datasets = task.build_datasets(cfg)
>   File "/data/hwj/EmotionRecognition/Emotion-LLaMA/minigpt4/tasks/base_task.py", line 59, in build_datasets
>     dataset = builder.build_datasets()
>   File "/data/hwj/EmotionRecognition/Emotion-LLaMA/minigpt4/datasets/builders/base_dataset_builder.py", line 58, in build_datasets
>     datasets = self.build()  # dataset['train'/'val'/'test']
>   File "/data/hwj/EmotionRecognition/Emotion-LLaMA/minigpt4/datasets/builders/image_text_pair_builder.py", line 34, in build
>     datasets[split] = dataset_cls(
>   File "/data/hwj/EmotionRecognition/Emotion-LLaMA/minigpt4/datasets/datasets/first_face.py", line 74, in __init__
>     self.tmp = [x.strip().split(' ') for x in open(ann_path)]
> FileNotFoundError: [Errno 2] No such file or directory: '/home/user/selected_face/face_emotion/relative_train_NCEV.txt'
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 15805) of binary: /home/ubuntu/anaconda3/envs/llama/bin/python
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/envs/llama/bin/torchrun", line 33, in <module>
>     sys.exit(load_entry_point('torch==2.0.0', 'console_scripts', 'torchrun')())
>   File "/home/ubuntu/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/home/ubuntu/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/home/ubuntu/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/home/ubuntu/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/home/ubuntu/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
> train.py FAILED
> 
> Failures:
>   <NO_OTHER_FAILURES>
> 
> Root Cause (first observed failure):
> [0]:
>   time      : 2024-12-20_21:53:27
>   host      : bmi4
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 15805)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

Could this issue be caused by the absence of the _relative_train_NCEV.txt_ file? If so, could you please let me know where I can download it or how to generate it?

Thank you for your time and assistance. I look forward to your response!

**Comment by ansucatherine** [comment]
I found the solution to this question in #30 where the authors have provided the related documents in [https://drive.google.com/drive/folders/1d-Sg5fAskt2s6OOEUNXFaM2u-C055Whj](url). 

Thank you again for your efforts!
