### ISSUE TITLE
Questions on evaluation settings and coarse-grained dict

### ISSUE THREAD

**Issue by ansucatherine** [ZebangCheng/Emotion-LLaMA#35]
Dear authors,

I would like to present my sincere thanks for your great work and for the efforts you've made to maintain this project. While running the code, I encountered some issues and have a few questions regarding the experiment settings:

# 1. Evaluation settings
When `running eval_emotion.py`, I used the following settings in `eval_emotion.yaml`:
```typescript
llama_model: "/data/EmotionRecognition/Emotion-LLaMA/checkpoints/Llama-2-7b-chat-hf"
ckpt: "/data/EmotionRecognition/Emotion-LLaMA/checkpoints/save_checkpoint/Emoation_LLaMA.pth"

eval_file_path: /data/EmotionRecognition/EmotionData/EMR2023/video/test-labels/test1-label.csv
img_path: /data/EmotionRecognition/EmotionData/EMR2023/video/mer2023test1&2/test1/
``` 

Additionally, in `first_face.py`, I set:
```python
self.task_pool = ["Emotion"] 
emos = ['neutral', 'angry', 'happy', 'sad', 'worried', 'surprise']
```
With these settings, I obtained a result lower than what is reported in the paper. Are there any additional settings or configurations that I might have missed which are necessary for reproducing the reported results?

# 2. Training tasks
Following the instructions, we need to set self.task_pool = ["emotion", "reason"] in `first_face.py`.

However, when I apply these settings, I encounter the following error:：
```typescript
caption = self.MERR_coarse_grained_dict[video_name]['caption']
KeyError: 'sample_00003127'
```
It seems this error is caused by certain samples appearing in the training set but missing in the coarse-grained dictionary. I have checked both files and found that there are a lot of such cases (as I have not checked all of them). Could you please advise on how to handle this issue?

Thank you again for your time and patience. I look forward to your guidance!

**Comment by ZebangCheng** [comment]
Thank you for your interest in our work and for bringing up this issue. 

1. It seems that you are testing on the MER2023 test1 dataset. Please note that the experimental results reported in our paper were conducted on the MER2023 test3 (MER-SEMI) dataset. The dataset you are using is different from ours. MER2023 test1 and test2 datasets include not only an emotion recognition classification task but also an emotion valence regression task. Due to the suboptimal performance of large models on the latter task, we did not perform experiments on test1 and test2 datasets.  

2. Regarding the `KeyError: 'sample_00003127'`, I have checked and found that the sample `'sample_00003127'` does not exist in the MERR dataset. This sample is part of the training set. When using the MERR dataset, please ensure that the dataset file paths are correctly specified in the dataset configuration file.  

https://github.com/ZebangCheng/Emotion-LLaMA/blob/66ae2feee62ac3a018b65d3c7fa26f65f494ceab/minigpt4/configs/datasets/firstface/featureface.yaml#L1-L10

I hope this helps resolve the issue. Let me know if you have further questions!

**Comment by ansucatherine** [comment]
Dear Authors,

Thank you so much for your detailed explanation. Under your guidance, I have successfully reproduced the evaluation results.

However, I still have some confusion regarding the training dataset. I noticed that you directly use the `MER2023/video` file for the `image_path`. I am unsure if I am using it correctly. Below are the settings of my `featuresface.yaml` file:

```bash
datasets:
  feature_face_caption:
    data_type: images
    
    build_info:
      image_path: /data/EmotionRecognition/EmotionData/EMR2023/video/mer2023train/train/

      ann_path: /data/EmotionRecognition/EmotionData/EMR2023/relative_train_NCEV.txt
      # ann_path: /home/user/selected_face/face_emotion/MERR_coarse_grained.txt
      # ann_path: /home/user/selected_face/face_emotion/MERR_fine_grained.txt
```
In this configuration, the image_path points to the training set of the MER2023 dataset, which I obtained from [this link](http://merchallenge.cn/datasets). Despite this, I am still encountering the same error.

Could you kindly confirm if this dataset setup is correct for training? I am wondering if I might have misunderstood your instructions or used an incorrect dataset or annotation file.

Thank you again for your time and assistance. I look forward to your response!

**Comment by ZebangCheng** [comment]
Thank you for providing feedback after successfully reproducing our results. 

First, let me explain why the `image_path` in our configuration points to `MER2023/video`. Initially, we used image paths directly. However, due to the privacy agreement associated with the dataset, we could not release facial images directly. Some researchers found it inconvenient to process videos and extract images from scratch. To address this, we modified the related code to load videos directly and extract the first frame as input for the Local Encoder. This makes reproduction easier.

Second, regarding the issue you encountered when using `MER2023/relative_train_NCEV.txt`, it seems to be the same error reported previously, which occurs when samples cannot be found. I suspect that the issue might be due to a typo in your file path. Could it be that you mistakenly used `EMR2023` instead of `MER2023`? If this is not the problem, could you please provide more details about the error you are encountering?

**Comment by ansucatherine** [comment]
Thank you very much for your response, and I apologize for the typo. To clarify, `EMR2023` is a folder I created specifically to store the MER2023 dataset, and all the data paths used in the code were directly copied. Therefore, the error does not seem to be caused by this typo.

The message of this error is reported as follows. I suspect that this issue might be due to a mismatch between the data I used to train the model and the captions provided in  `MERR_coarse_grained.json`.  Specifically, I’m wondering if the training data should come from a dataset other than the training set of MER2023 (for clarity, I am referring to the folder containing files such as`sample_00000000.avi`, `sample_00000001.avi`, ..., `sample_00007028.avi`)?

Could you kindly confirm whether the MER2023 training set is the correct dataset to use, or if a different dataset should be utilized for training?

```bash
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/llama/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/llama/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/llama/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/EmotionRecognition/Emotion-LLaMA/minigpt4/datasets/datasets/first_face.py", line 140, in __getitem__
    caption = self.MERR_coarse_grained_dict[video_name]['caption']
KeyError: 'sample_00003127'
```

**Comment by ZebangCheng** [comment]
I understand your question. If you want to use `MERR_coarse_grained.json` and `MERR_fine_grained.json`, you should not use `relative_train_NCEV.txt` in the dataset configuration file `featuresface.yaml`. Instead, you should use the corresponding `MERR_coarse_grained.txt` and `MERR_fine_grained.txt` files.

To clarify, we did not use the training set of the MER2023 dataset (i.e., `/relative_train_NCEV.txt`) to train Emotion-LLaMA. The reason is that we trained an Attention model on the MER2023 training set as part of the MER2023 Baseline. This model was then used to generate pseudo-labels for unlabeled videos in the MER2023-SEMI dataset (i.e., the emotion category labels in `MERR_coarse_grained.txt` and `MERR_fine_grained.txt`). Considering that the distribution of pseudo-labels is consistent with `relative_train_NCEV.txt`, we decided to use only the MERR dataset to train Emotion-LLaMA and did not include the training set of the MER2023 dataset for training.

```
MERR_coarse_grained.json => MERR_coarse_grained.txt
MERR_fine_grained.json => MERR_fine_grained.txt
```

**Comment by ansucatherine** [comment]
Many thanks for your kind help!  I am delighted to share that I was finally able to train the model successfully. To assist others who might encounter the same issues, I have summarized my settings below for reference:

**Data**
As the authors have mentioned above, the EmotionLLaMA were performed on the MER2023 test3 (MER-SEMI) dataset, which corresponds to the `MER2023train/test3` folder obtained from the MER2023 dataset link.

**Evaluation**
The checkpoint files `Emoation_LLaMA.pth` and `stage2/checkpoint_best.pth` correspond to the training results of stage1 and stage2, respectively. Therefore, to reproduce the results in the paper, I set `ckpt` to `stage2/checkpoint_best` in `eval_emotion.yaml`

**Training**
To use `MERR_coarse_grained.json` and `MERR_fine_grained.json` in the training stage, I have the following settings in `featureface.yaml`:
```
    build_info:
      image_path: /data/EmotionRecognition/EmotionData/EMR2023/video/mer2023train/test3/

      ann_path: /data/EmotionRecognition/EmotionData/EMR2023/MERR_coarse_grained.txt
```

Thank you once again for this work and for your continued support and guidance. Wishing you all the best with your future research endeavors!
